// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDp4kDJnSkjpcljceYfftt1xGsiKPO1v4',
    appId: '1:734010285466:web:dc2eca06427295c3b1ee23',
    messagingSenderId: '734010285466',
    projectId: 'philosophy-app-481217',
    authDomain: 'philosophy-app-481217.firebaseapp.com',
    storageBucket: 'philosophy-app-481217.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABJqS35PwUbSctUSSw0tq8Qd2oiN4XrZU',
    appId: '1:734010285466:android:7c266af52971cf60b1ee23',
    messagingSenderId: '734010285466',
    projectId: 'philosophy-app-481217',
    storageBucket: 'philosophy-app-481217.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxdi2noYpcMCJQvvgDHSWR27yFDsfEaSQ',
    appId: '1:734010285466:ios:55a5526bac2efbd1b1ee23',
    messagingSenderId: '734010285466',
    projectId: 'philosophy-app-481217',
    storageBucket: 'philosophy-app-481217.firebasestorage.app',
    iosClientId: '734010285466-pke5osr4jg3an8mjc2rq08k9tg15kh10.apps.googleusercontent.com',
    iosBundleId: 'com.example.philoshophyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxdi2noYpcMCJQvvgDHSWR27yFDsfEaSQ',
    appId: '1:734010285466:ios:55a5526bac2efbd1b1ee23',
    messagingSenderId: '734010285466',
    projectId: 'philosophy-app-481217',
    storageBucket: 'philosophy-app-481217.firebasestorage.app',
    iosClientId: '734010285466-pke5osr4jg3an8mjc2rq08k9tg15kh10.apps.googleusercontent.com',
    iosBundleId: 'com.example.philoshophyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDp4kDJnSkjpcljceYfftt1xGsiKPO1v4',
    appId: '1:734010285466:web:a00c2b2849c1f0b7b1ee23',
    messagingSenderId: '734010285466',
    projectId: 'philosophy-app-481217',
    authDomain: 'philosophy-app-481217.firebaseapp.com',
    storageBucket: 'philosophy-app-481217.firebasestorage.app',
  );
}
